package TestClass;

import java.io.IOException;
import javax.mail.MessagingException;
import org.testng.ITestResult;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.Test;
import Pomclass.FilterWithinResult;
import Pomclass.Login;
import UtilityClass.UtilityClass;
import generic.ConfingData_provider;
import generic.ForMultiplemailReceipent;
import generic.NewBaseTest;
import generic.RetryAnalyzer;
import io.qameta.allure.Description;
import io.qameta.allure.Epic;
import io.qameta.allure.Feature;
@Epic("SearchFilter")
@Feature("Verify Filter within Results")
public class FilterResult extends NewBaseTest{
	
	
	
	@Test(retryAnalyzer = RetryAnalyzer.class)
	@Description("Verify the Filter within results functionaitly")
	public void verifysearchfilter() throws InterruptedException, IOException
	
	{
		Login log= new Login(driver);
		
		 log.login(ConfingData_provider.Email,ConfingData_provider.Password);
		FilterWithinResult res =new FilterWithinResult (driver);
	res.verifyfilterwithinresult(driver);	
	
	}
	@AfterMethod
	public void finish(ITestResult result) throws IOException, MessagingException
	{
	if(ITestResult.FAILURE==result.getStatus())
	{
		String screenshot=  UtilityClass.Capaturescreenshot(driver,result.getName() );
		String testUrl = driver.getCurrentUrl();  
		 ForMultiplemailReceipent.sendEmail(
           	   driver, new String[]{"ghodake6896@gmail.com"},
           	    " Search Filter Within Result",
           	    "Please check issue coming in search filter within in results, please find the attached screenshot for details." ,
           	 screenshot , testUrl
           	   
           	);
	
	}
	
	}
}
